"""Generated by chatGPT from the MuJoCo xml."""

from vuer.schemas import Box, PointLight, Sphere, Plane

default_mat = dict(
    materialType="depth",
    # materialType="standard",
    # material=dict(emissive="#222", roughness=0.01, color="#b1b1c2"),
)

transparent_mat = dict(
    materialType="depth",
    # material=dict(
    #     emissive="#555",
    #     roughness=0.1,
    #     color="#555",
    #     transparent=True,
    #     opacity=0.3,
    # ),
)
_Box = lambda **kwargs: Box(**kwargs, **default_mat)


class BgSphere(Sphere):
    def __init__(self, color, materialType="phong"):
        super().__init__()

        self.key = "background-sphere"
        self.materialType = materialType
        self.args = [50, 20, 20]
        self.position = [0, 0, 0]
        self.materialType = "basic"
        self.material = dict(color=color, side=2)


scene = [
    BgSphere(color="#b1b1c2", materialType="basic"),
    PointLight(color="white", intensity=10, position=[0, 2, 0]),
    PointLight(color="white", intensity=15, position=[-3, 2, 2.5]),
    Plane(args=[16, 10], color="red", key="ground-plane", position=[2.5, 0, 0], **default_mat),
    _Box(args=[1, 2, 0.2], color="gray", key="step-01", position=[2, 0, 0.1]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-02", position=[2.35, 0.0, 0.2]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-03", position=[2.7, 0.0, 0.4]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-04", position=[3.05, 0.0, 0.6]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-05", position=[3.4, 0.0, 0.8]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-06", position=[3.75, 0.0, 1.0]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-07", position=[4.1, 0.0, 1.2]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-08", position=[4.45, 0.0, 1.4]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-09", position=[4.8, 0.0, 1.6]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-10", position=[5.15, 0.0, 1.8]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-11", position=[5.5, 0.0, 2.0]),
    _Box(args=[1, 2, 0.4], color="gray", key="step-12", position=[5.85, 0.0, 2.2]),
    _Box(args=[4, 2, 0.4], color="gray", key="step-13", position=[7.75, 0.0, 2.4]),
    _Box(args=[9, 0.2, 5], color="gray", key="wall-left", position=[6, 1.1, 2.5]),
    Box(args=[9, 4, 3], color="gray", key="wall-right", position=[6, -1 - 2.0, 1.5], **transparent_mat),
    _Box(args=[0.2, 6, 8], color="gray", key="wall-back", position=[10, -1.1, 4]),
]
