JYNS_USERNAME: <username>
JYNS_PASSWORD: <password>
JYNS_HOME: <home directory, see .jaynes.yml for more details.>
JYNS_HOST: <ip-address of the target machine>
LUCIDSIM_EVAL_DATASETS:
JYNS_AWS_S3_BUCKET: <bucket-id>